name: Build & Package VSIX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Single job to build and package VSIX using sql.js (no native binaries needed)
  package-vsix:
    name: Build and package VSIX
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        shell: bash
        run: |
          echo "Installing dependencies..."
          npm ci

      - name: Install vsce
        shell: bash
        run: |
          npm install -g @vscode/vsce

      - name: Build extension with webpack
        shell: bash
        run: |
          echo "Building extension with webpack..."
          npm run package

      - name: Verify VSIX packaging structure
        shell: bash
        run: |
          echo "Verifying extension structure..."
          echo "Checking for sql.js wasm file:"
          ls -la dist/assets/sql-wasm.wasm || echo "WASM file not found"
          
          echo "Checking compiled extension:"
          ls -la dist/extension.js || echo "Extension JS not found"

      - name: Package VSIX
        shell: bash
        run: |
          echo "Packaging VSIX..."
          vsce package --no-yarn --out claude-context-manager.vsix
          
          echo "VSIX package created successfully:"
          ls -la claude-context-manager.vsix
          echo "Package size: $(du -h claude-context-manager.vsix | cut -f1)"

      - name: Upload VSIX
        uses: actions/upload-artifact@v4
        with:
          name: claude-context-manager.vsix
          path: claude-context-manager.vsix

  # Validate VSIX on multiple platforms
  validate-vsix:
    name: Validate VSIX on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: package-vsix
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Download VSIX artifact
        uses: actions/download-artifact@v4
        with:
          name: claude-context-manager.vsix
          path: .

      - name: Install dependencies for validation script
        shell: bash
        run: |
          echo "Installing dependencies for validation..."
          npm ci

      - name: Run VSIX validation script
        shell: bash
        run: npm run test:vsix